### ISSUE TITLE
프렌들리숍 작업

### ISSUE THREAD

**Issue by koipkoi** [koipkoi/pokeemerald-ko#17]
![pokeemerald_01](https://user-images.githubusercontent.com/39587773/68676315-20695600-059d-11ea-9ff4-19be8f9bb6ef.png)

바이트수 확장이 필요했던 아이템명에서 발생

**Comment by poketony** [comment]
왼쪽 위에 999999원 단위 짤리는 것도 수정해야 할 것 같습니다.
![pokeruby_01](https://user-images.githubusercontent.com/57011422/74949540-38286400-5441-11ea-9114-f6d1a73eb6fe.png)
루비 버전은 이렇습니다.
