### ISSUE TITLE
Game does not run on VBA

### ISSUE THREAD

**Issue by Wintiger0222** [koipkoi/pokeemerald-ko#2]
![Cap 2019-04-13 11-09-03-950](https://user-images.githubusercontent.com/24960466/56073330-e18fd980-5ddc-11e9-95cb-f12b3412abec.jpg)
컴파일해서 실행해 본 결과 NO$GBA 2.6에서는 돌아가지만 VBA 1.7.2와 1.8.0에서는 작동하지 않네요.

**Comment by koipkoi** [comment]
vba 설정에서 저장방식을 바꾸시면 정상적으로 실행될겁니다.

**Comment by Wintiger0222** [comment]
깜박했습니다. 고맙습니다.
