### ISSUE TITLE
‘ 문자 인식 불가(컴파일 불가 문제)

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#20]
![캡처](https://user-images.githubusercontent.com/57011422/74524265-0c4d4000-4f62-11ea-94d4-7f280a5b8bfa.PNG)

루비나 사파이어에서는 ‘ 문자를 써도 딱히 컴파일 오류가 안 났었는데
에메랄드에서는 쓰면 컴파일 오류가 납니다. 
루비 사파이어에서는 ‘ 를 쓰면 인게임 내에서는 '로 출력이 됩니다.
에메랄드에서도 똑같이 적용되도록 해주시면 감사하겠습니다.

**Comment by poketony** [comment]
![pokeruby_01](https://user-images.githubusercontent.com/57011422/74524504-7ebe2000-4f62-11ea-81d7-87563efc75c4.png)

해당 리소스가 이렇게 적용이 되면 됩니다

**Comment by koipkoi** [comment]
‘ 대신에 '를 써야합니다.
빌드 오류나는 부분은 제가 수정하겠습니다.
그리고 왠만하면 charmap 수정은 문제가 많이 생길 것 같아 보류해야할 것 같습니다.
