### ISSUE TITLE
포켓몬스넥케이스 폰트 조절

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#21]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/74946683-0a412080-543d-11ea-9df5-48e6f223d5fb.png)
에메랄드에서 폰트가 너무 커서 잘립니다.

![pokeruby_02](https://user-images.githubusercontent.com/57011422/74946723-175e0f80-543d-11ea-8469-3142ac8b5b96.png)
루비/사파이어 버전 참고하셔서 이렇게 수정해 주세요!

**Comment by poketony** [comment]
추가로 "케이스를 닫는다" 등 이 출력되는 박스 메시지도 
폰트를 통일해야 될 것 같습니다

**Comment by koipkoi** [comment]
![pokeemerald_01](https://user-images.githubusercontent.com/39587773/75095453-2a591700-55d8-11ea-90ce-94fef9683e43.png)

Lv 부분은 없애야 할까요?

**Comment by poketony** [comment]
> ![pokeemerald_01](https://user-images.githubusercontent.com/39587773/75095453-2a591700-55d8-11ea-90ce-94fef9683e43.png)
> 
> Lv 부분은 없애야 할까요?

아 그럼 다시 8pt로 바꿔주세요, 역으로 루비/사파이어의 폰트를 바꿔야겠네요.
답변 늦어서 죄송합니다
