### ISSUE TITLE
포켓몬 스테이터스 창 경험치에 "앞으로" 추가

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#22]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/74957751-57c48a00-544b-11ea-8e70-e2834b5a7364.png)
![pokeruby_02](https://user-images.githubusercontent.com/57011422/74957756-58f5b700-544b-11ea-8960-dfda2ccc49d8.png)
루비/사파이어 버전과 같게 바꿔주시면 됩니다!

**Comment by poketony** [comment]
그리고 지닌물건이 출력되는 위치가 바뀌어야 할 것 같습니다.
"없음" 부분을 루비/사파이어처럼 왼쪽 칸으로 끌어당겨 주세요!

**Comment by koipkoi** [comment]
#18 로 이동했습니다.
