### ISSUE TITLE
도감 리스트 폰트 수정

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#26]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/75670533-420f5a00-5cc0-11ea-99a7-2c39dcdc50ea.png)
포켓몬 이름이 뜨는 부분을 갈무리 10pt로 교체해 주세요
![pokeruby_01](https://user-images.githubusercontent.com/57011422/75670536-4471b400-5cc0-11ea-824a-2cc7d685db63.png)

**Comment by koipkoi** [comment]
#10 과 겹치기 때문에 닫겠습니다.
