### ISSUE TITLE
포켓몬 스테이터스 창 일어판처럼 교체

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#27]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/76147418-62378280-60df-11ea-9bee-5cadd7d236dd.png)

현재 버전 스크린샷인데(세 줄)

![5  POKEMON_EMER_BPEJ00_01](https://user-images.githubusercontent.com/57011422/76147422-69f72700-60df-11ea-9d7c-f686265843dd.png)
일본판은 두 줄입니다. 두 줄로 맞추는 텍스트 수정은 이미 끝내놓았으니 그래픽만 수정해주시면 됩니다.

**Comment by poketony** [comment]
아 근데 프로필이나 특성 등이 적혀 있는 부분 영역 길이가 다르네요 저 부분은 제가 일단 나중에 시간 나면 수정하겠습니다

**Comment by poketony** [comment]
해당 화면 외에도 타일 배열 파일(.bin)파일 여러 개를 수정해야 하니 참고해 주세요.
또한 좌측 부분(닉네임/원 포켓몬명) 또한 다르니 이쪽도 수정해 주세요.
생각보다 많이 난감한 수정사항이 될 듯 합니다...

**Comment by koipkoi** [comment]
#18 으로 옮겼습니다.
