### ISSUE TITLE
트레이너 카드 이름 출력 위치

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#28]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/76445171-582bc180-6408-11ea-8549-a77b7b3b1e70.png)

이름과 플레이어 이름의 간격을 띄워주시면 됩니다

**Comment by poketony** [comment]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/77320782-87b9c280-6d54-11ea-8716-ad579f748634.png)

자력으로 해결했습니다. 별 거 아니었네요

**Comment by koipkoi** [comment]
다음부터 문제 해결하셨으면 내역 남길때 제목을 'fixed #이슈번호'로 남겨 주시면 감사하겠습니다. 

수정사항 내역을 볼 수 있게끔 하기위함입니다!

그리고 fixed 안붙이도 #만 붙이시고 직접 닫는것도 괜찮습니다.

**Comment by poketony** [comment]
아 넵! 다음부터는 그렇게 처리하도록 하겠습니다

2020년 3월 23일 (월) 오후 10:29, koipkoi <notifications@github.com>님이 작성:
