### ISSUE TITLE
배틀 팩토리 대여 화면

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#30]
![pokeemerald_01](https://user-images.githubusercontent.com/57011422/76596433-7fd27500-6541-11ea-9860-070aef930df8.png)

폰트가 잘리는 부분이 있어서 출력 위치를 수정하시거나 폰트를 교체해야 될 것 같습니다.

아래는 일어판 원본입니다

![5  POKEMON_EMER_BPEJ00_01](https://user-images.githubusercontent.com/57011422/76596465-9973bc80-6541-11ea-8eac-1afe281c7245.png)

남은 작업
- [x] 폰트 교체
- [x] 상단 "포켓몬" 카테고리 여백 제거

**Comment by koipkoi** [comment]
폰트를 8x16사이즈로 변경하면 괜찮아 보이는데 어떻게 생각하시나요?

**Comment by poketony** [comment]
> 폰트를 8x16사이즈로 변경하면 괜찮아 보이는데 어떻게 생각하시나요?

네 그렇게 해주세요! 
그리고 혹시 위쪽의 '집게 포켓몬'이 '집게포켓몬'으로 붙여 써지게 해주실 수 있나요?

**Comment by koipkoi** [comment]
네, 수정하고 닫을게요.

**Comment by koipkoi** [comment]
"... 포켓몬" 표시하는 부분은 배틀 팩토리 화면 말고도 2곳 사용되고 있습니다.


- 도감 화면
- 스타팅 포켓몬 선택 화면

위 부분도 같이 수정될텐데 괜찮을까요?

**Comment by poketony** [comment]
네 원래부터 그 표기가 맞는지라 한번에 수정되면 오히려 좋습니다!
