### ISSUE TITLE
리소스 빌드 오류

### ISSUE THREAD

**Issue by poketony** [koipkoi/pokeemerald-ko#6]
![캡처](https://user-images.githubusercontent.com/57011422/67666089-64116c80-f9ae-11e9-89cb-0462509d2613.PNG)

다소 긴 아이템 명(ex. 포켓몬스넥케이스, 벌레회피스프레이, 성호에게줄편지, 기술머신케이스 etc)으로 인해 빌드가 실패하는 오류가 발생함, 
원인은 본래 각 아이템마다 지정된 이름의 바이트보다 
수정된 아이템 명의 바이트가 크기 때문으로 보임.
본래 할당되는 바이트 크기를 새롭게 지정해주면 해결될 것으로 추측.

**Comment by poketony** [comment]
![캡처](https://user-images.githubusercontent.com/57011422/67666658-97083000-f9af-11e9-9698-45a02c657281.PNG)

아이템 명 뿐만이 아니라, 기술 이름이나 트레이너 클래스 등에 걸쳐 광범위하게 나타나는 듯함.

**Comment by koipkoi** [comment]
일단 글자수에 맞춰서 병합했습니다.
주석달아놨으니 나중에 확장하면 주석참고해서 수정하면 될것같습니다.
이슈는 열어두겠습니다.^^

**Comment by koipkoi** [comment]
1. 기술명 확장 (14 > 16)
    MOVE_NAME_LENGTH 수정

2. 아이템명 확장 (14 > 18)

3. 트레이너 분류명 확장 (13 > 16)

**Comment by koipkoi** [comment]
4. 주석처리된 문자열을 재입력

**Comment by poketony** [comment]
> 1. 주석처리된 문자열을 재입력
 리소스에 적용이 된 건가요?
